// Navigation
export const NAVIGATE_BACK = 'NAVIGATE_BACK'

// Register new user
export const REGISTER_STARTED = 'REGISTER_STARTED'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

// Login user
export const LOGIN_STARTED = 'LOGIN_STARTED'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_STARTED = 'LOGOUT_STARTED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

// Get authenticated user profile
export const GET_AUTHENTICATED_USER_STARTED = 'GET_AUTHENTICATED_USER_STARTED'
export const GET_AUTHENTICATED_USER_SUCCESS = 'GET_AUTHENTICATED_USER_SUCCESS'
export const GET_AUTHENTICATED_USER_FAILURE = 'GET_AUTHENTICATED_USER_FAILURE'

// Get authenticated user settings
export const GET_USER_SETTINGS_STARTED = 'GET_USER_SETTINGS_STARTED'
export const GET_USER_SETTINGS_SUCCESS = 'GET_USER_SETTINGS_SUCCESS'
export const GET_USER_SETTINGS_FAILURE = 'GET_USER_SETTINGS_FAILURE'

// Update authenticated user settings
export const UPDATE_USER_SETTINGS_STARTED = 'UPDATE_USER_SETTINGS_STARTED'
export const UPDATE_USER_SETTINGS_SUCCESS = 'UPDATE_USER_SETTINGS_SUCCESS'
export const UPDATE_USER_SETTINGS_FAILURE = 'UPDATE_USER_SETTINGS_FAILURE'

// Get all items
export const RESET_ITEMS = 'RESET_ITEMS'
export const GET_ITEMS_STARTED = 'GET_ITEMS_STARTED'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE'

// Get all users
export const RESET_USERS = 'RESET_USERS'
export const GET_USERS_STARTED = 'GET_USERS_STARTED'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

// Get user by username
export const RESET_USER = 'RESET_USER'
export const GET_USER_BY_USERNAME_STARTED = 'GET_USER_BY_USERNAME_STARTED'
export const GET_USER_BY_USERNAME_SUCCESS = 'GET_USER_BY_USERNAME_SUCCESS'
export const GET_USER_BY_USERNAME_FAILURE = 'GET_USER_BY_USERNAME_FAILURE'

// Upload image
export const UPLOAD_IMAGE_STARTED = 'UPLOAD_IMAGE_STARTED'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE'

// Search items
export const SEARCH_ITEMS_RESET = 'SEARCH_ITEMS_RESET'
export const SEARCH_ITEMS_STARTED = 'SEARCH_ITEMS_STARTED'
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS'
export const SEARCH_ITEMS_FAILURE = 'SEARCH_ITEMS_FAILURE'
