// Navigation
export const NAVIGATE_BACK = 'NAVIGATE_BACK'

// Register new user
export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

// Login user
export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT_START = 'LOGOUT_START'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

// Get authenticated user settings
export const GET_USER_SETTINGS_START = 'GET_USER_SETTINGS_START'
export const GET_USER_SETTINGS_SUCCESS = 'GET_USER_SETTINGS_SUCCESS'
export const GET_USER_SETTINGS_FAILURE = 'GET_USER_SETTINGS_FAILURE'

// Update authenticated user settings
export const UPDATE_USER_SETTINGS_START = 'UPDATE_USER_SETTINGS_START'
export const UPDATE_USER_SETTINGS_SUCCESS = 'UPDATE_USER_SETTINGS_SUCCESS'
export const UPDATE_USER_SETTINGS_FAILURE = 'UPDATE_USER_SETTINGS_FAILURE'

// Get all items
export const RESET_ITEMS = 'RESET_ITEMS'
export const GET_ITEMS_START = 'GET_ITEMS_START'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE'

// Get all users
export const RESET_USERS = 'RESET_USERS'
export const GET_USERS_START = 'GET_USERS_START'
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS'
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE'

// Get user by username
export const RESET_USER = 'RESET_USER'
export const GET_USER_BY_USERNAME_START = 'GET_USER_BY_USERNAME_START'
export const GET_USER_BY_USERNAME_SUCCESS = 'GET_USER_BY_USERNAME_SUCCESS'
export const GET_USER_BY_USERNAME_FAILURE = 'GET_USER_BY_USERNAME_FAILURE'

// Upload image
export const UPLOAD_IMAGE_START = 'UPLOAD_IMAGE_START'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE'
